export const ThreedProjects = [
    {
        id: 1,
        contentType: 'threed',
        title: 'Lighthouse Town',
        description: 'Simple low-poly render of a simple oceanside town in the mist.',
        pic1Path: 'contentsource/ThreedProjects/LightHouseTown/lighthouserender.png',
        pic2Path: 'contentsource/ThreedProjects/LightHouseTown/lighthousevertcycles.png',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
    },
    {
        id: 2,
        contentType: 'threed',
        title: 'Sword in the Stone',
        description: 'A simple sword that I modeled and rendered, made for a game I was working on. The game is no longer with us ;-;',
        pic1Path: 'contentsource/ThreedProjects/SwordStone/swordstone.png',
        pic2Path: 'contentsource/ThreedProjects/SwordStone/swordcycles.png',
        media1: true,
        media2: false,
        layout1: 'vertical',
        layout2: 'vertical',
    },
    {
        id: 3,
        contentType: 'threed',
        title: 'Sword Rack',
        description: 'The second render I ever created, a couple swords on a rack.',
        pic1Path: 'contentsource/ThreedProjects/SwordRack/secondrender.png',
        pic2Path: 'contentsource/ThreedProjects/SwordRack/rackvertrender.png',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
    },
    {
        id: 4,
        contentType: 'threed',
        title: 'My First Render',
        description: 'The first render I created with blender :). A little green fan on a table.',
        pic1Path: 'contentsource/ThreedProjects/FirstRender/firstrender.png',
        pic2Path: 'contentsource/ThreedProjects/FirstRender/foldingfanvert.png',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
    },
]