import React from "react";

const ImposterSyndrome = () => {
    return(
        <div className="flex items-center flex-col m-10 space-y-5">
            <div className='md:w-9/12 font-inter md:outline outline-1 shadow-stone-500 outline-stone-400 md:shadow-md md:p-10'>
                <div className='font-inter text-center mb-10 font-bold text-6xl'>
                            Imposter Syndrome; a short story by me
                </div>
                <div className=' font-semibold text-2xl mt-5'>
                        Postmortem
                </div>
                <p className='mt-5 indent-5'>Another story I wrote for a class, this one is definitely something of a departure from what the kind of stuff I usually like to write and a step outside of my comfort zone. I was really into Kafka at the time so I wanted to create a story that was whacky and weird and a bit surreal. Not sure how I did, but I can say that there is at least one glaring plothole in the story; lmk if you find it :)</p>
                <h2 className='font-semibold text-2xl mt-5'>Imposter Syndrome</h2>
                <p className='mt-5 indent-5'>On an autumn day, Patrick Durham stepped onto the morning train at the station just outside of his high-rise apartment. Constructed of glass and steel, the railway overlooked the massive metropolis that Patrick called home. A glinting skyline faded into the hazy sky, and as the train took off, rain began to fall. As Patrick waited for the train to arrive at his workplace, passengers flowed into the car at every stop. Like him, they donned business-casual attire in various shades of black, grey, and white. Patrick couldn’t help but notice the mundanity of it all; legions of men and women in suits on their way to fulfill their role as cogs in a self-perpetuating machine. I’m different, Patrick thought. I’ve figured out the system.</p>
                <p className='mt-5 indent-5'>After a time, the train arrived at Patrick’s stop. He stepped out onto the platform, surrounded by a mass of employees, each deftly maneuvering through the crowd to avoid being late for work. Filtered by an ocean of umbrellas, the grandeur of the corporate skyscraper before them was still apparent. Patrick appreciated the rain today; anything to break up the monotony of his workday.</p>
                <p className='mt-5 indent-5'>After getting his coffee from the café next door, Patrick ascended the elevator up to his office floor. As a principal software developer, this meant a ride to a level of the building that most lower-tier developers and workers would only ever dream of. When the elevator doors opened, Patrick’s heart dropped as his boss, Jacob, instantly greeted him with a smile. </p>
                <p className='mt-5 indent-5'>“Hey Patrick. Good to see you, man! Sent you some code that Heather was working on as part of the Pendleton Project. It needs fixing. We’re not quite sure where the issue is.”</p>
                <p className='mt-5 indent-5'>Patrick put on his best faux smile as he responded, “Sure thing. I’ll do what I can”.</p>
                <p className='mt-5 indent-5'>Patrick had always found his interactions with Jacob to be somewhat strained. Sure, the man saw Patrick as something of a gift from God. From his perspective, Patrick was a great problem-solver with a penchant for writing functional code faster than pretty much anyone else working under the company. However, Patrick saw things quite differently. To him, every conversation with Jacob felt like a strange game he played; pretending that the work he was being assigned would be difficult to complete, pretending that the work he finished yesterday morning took him until yesterday evening, pretending that he actually knows what he’s talking about. It didn’t help that Jacob often seemed like less of a human and more of a corporate robot.</p>
                <p className='mt-5 indent-5'>At his desk, Patrick immediately got to work on the task in his email. The tool that his coworker Heather had been working working on was somewhat complex, and Patrick quickly realized that he definitely wouldn’t be able to fix whatever strange concoction of errors her code was creating. This tended to happen a lot with Heather; as a high-level developer herself, she often would attempt to create intricate, advanced solutions to every problem she encountered, causing her to end up with programs filled to the brim with small issues that her initial implementation had overlooked. Instead of bothering to fix all of them, Patrick simply restarted from scratch; a couple well-placed searches on the internet quickly yielded a few solutions to his problem, created by other programmers in some other place. Copy, paste, a few edits, and Patrick’s ‘new’ tool was created, all within a half-hour. At this, Patrick chuckled to himself at the simplicity of his job. He scheduled an email to be sent to Heather’s inbox in a couple hours’ time:</p>
                <p className='mt-5 indent-5'>“Hey, had some trouble figuring out your code, maybe this might be a better solution? - RD”.</p>
                <p className='mt-5 indent-5'>Now that he had some extra time on his hands, Patrick thought about how he should spend his morning. After working at this company for numerous years, Patrick had long-since learned all the secrets of its headquarters, and long-since taken in the views of all its best spots. These days, he defaulted to simply sitting at his desk throughout the day, listening to music, and watching films. Today, he defaulted to the usual; a new flick from one of his favorite directors — he had become something of a film buff.</p>
                <p className='mt-5 indent-5'>Patrick ate lunch alone, as he did most days. Most of his coworkers had noticed how much of a favorite of Jacob’s he had become, and generally chose to avoid him. Once he had finished eating, he decided to ask Jacob for another task. Normally, something like the work he’d completed earlier would have been enough for a day, but the scowl Heather had shot him from across the room after she received his email had invigorated him. Patrick shot Jacob a quick email:</p>
                <p className='mt-5 indent-5'>“Finished Heather’s thing. Anything else I can help with? - RD”.</p>
                <p className='mt-5 indent-5'>Moments later, a response.</p>
                <p className='mt-5 indent-5'>“Absolutely! Pretty basic task, some new guy in R&D just needs you to automate reading in some files. Thanks Patrick, you’re doing great! Sincerely, Jacob Thompson”.</p>
                <p className='mt-5 indent-5'>Patrick rolled his eyes at Jacob’s seemingly endless excitement at the prospect of completing something that had already been done hundreds of times before, but he was glad Jacob had laid something relatively simple on his plate. The chip placed on his shoulder by Heather’s annoyed glance had crumbled, and he was happy the only thing that stood between himself and an evening of relaxation was a couple minutes of work. In a matter of seconds, Patrick searched the internet for some simple document parsing code. To his surprise, his web browser returned an error: No internet.</p>
                <p className='mt-5 indent-5'>Momentarily, an announcement jingle played over a loudspeaker, and a robotic-sounding woman’s voice spoke over the intercom:</p>
                <p className='mt-5 indent-5'>“Due to an unexpected compromise in our infrastructure, internet connection throughout the city has been suspended. We are working to fix this problem. Thank you!”</p>
                <p className='mt-5 indent-5'>A collective groan could be heard throughout the office floor. For a moment, Patrick sat at his desk in a bit of a shock. In his several years with the company, this hadn’t happened before. He had never been unable to access the internet for a task. Due to the profile and size of the company itself, it was extremely rare for such an outage to occur. Oh well, Patrick thought to himself. I’ll just do it on my own. Patrick opened up a new file and started coding. Although it had been years since the last time he had actually coded anything on his own, he had copy and pasted similar code enough times that he was able to finish most of the program on his own. In the back of his mind, the part that had begun to worry he’d have to wait until the internet came back before he could finish his assignment went quiet. After a few minutes, Patrick was finished coding, and he tried running the program. He waited a moment before the screen tinted red, and a couple of error messages appeared. Certain that his code should have worked, he scanned the console to see what information he could garner from the errors.</p>
                <p className='mt-5 indent-5'>“OutOfMemoryException: Exception of type ‘System.OutOfMemoryException’ was thrown.”</p>
                <p className='mt-5 indent-5'>Patrick stared at the red text on his screen for a moment and scratched his head. A scan of his code left him confused as ever. He didn’t see any way that the code he wrote could have resulted in that error. His eyes began to glaze over as he realized that this usually trivial problem now had him completely stumped. He glanced at the other developers seated around him. Although the internet had gone out, they worked as busily as ever, eyes glued to their screens. Patrick began to panic. Had relying on the internet to efficiently solve problems for so long left him incapable of writing even simple code? How had he, a complete fraud, managed to slip through the cracks, managed to achieve such high standing within this company. He thought of his cushy apartment, his beautiful view of the skyline, his wardrobe full of expensive suits. His body began to feel hot.</p>
                <p className='mt-5 indent-5'>Calm down, Patrick thought to himself. Maybe you’ve slipped a little bit, but this is a low-stakes situation. In a couple hours the internet will come back and you’ll go back to being the most effective developer in the room. After a couple more minutes of positive self-affirmations, Patrick began to relax. He decided he’d pass time until the internet came back by trying any solution he could find to the problem, if for no other reason than to repair his damaged ego.</p>
                <p className='mt-5 indent-5'>A few hours passed, and Patrick, trying everything he could think of, still had nothing. The internet had yet to return, so Patrick decided he would ask one of his coworkers for help. He stood from his desk and walked over to his closest neighbor — a man named Jerry — who was one of the only developers senior to him.</p>
                <p className='mt-5 indent-5'>“Hey Jerry. Mind helping me with something real quick?” Jerry looked at him with slight bewilderment.</p>
                <p className='mt-5 indent-5'>“You need help?” Jerry chuckled. “I don’t think you’ve ever asked me for help with your code. What could possibly have the great Patrick Durham stumped?”, he asked sarcastically. Cringing internally, Patrick managed to produce a small chuckle.</p>
                <p className='mt-5 indent-5'>“Just trying to figure out an annoying little error.” Jerry stood up and followed Patrick back to his desk. Patrick gestured toward the screen, and Jerry took a moment to examine the code, and the error.</p>
                <p className='mt-5 indent-5'>A slight frown ran along Jerry’s face. “What exactly are you trying to do here?”</p>
                <p className='mt-5 indent-5'>“Just making a quick document parser.” Patrick shrugged. “Any ideas?”</p>
                <p className='mt-5 indent-5'>Jerry shot Patrick an angry look that caught him off guard. “Are you trying to mock me?”</p>
                <p className='mt-5 indent-5'>“What?”, asked Patrick.</p>
                <p className='mt-5 indent-5'>“Look, man. We all know you’re good at your job. That’s great for you. But that doesn’t mean you can act like we’re stupid.” Jerry turned and began to walk back to his desk. “Christ”, he muttered under his breath.</p>
                <p className='mt-5 indent-5'>Patrick looked on in disbelief. He thought to himself, Did that really just happen? Patrick sat down at his desk, and finally gave up. He decided he’d just wait until the internet came back on, whenever that may be. Glancing back at the screen in front of him, Patrick noticed a small alert at the top left of the screen.</p>
                <p className='mt-5 indent-5'>“Task Timer Overflow: Please Report to Supervisor.”</p>
                <p className='mt-5 indent-5'>The task timer. Because he rarely took much time to complete his work, Patrick had completely forgotten about this legacy system that triggered whenever a developer took too long to submit whatever work they’d been assigned. He sighed to himself and walked over to Jacob’s office. At his desk, Jacob appeared to be deeply engrossed in some paperwork. Patrick gave the door a light knock.</p>
                <p className='mt-5 indent-5'>“Hey.” Jacob stopped writing and glanced up at him. “Got a task timer overflow. It said to report to you?” Jacob’s eyebrows raised.</p>
                <p className='mt-5 indent-5'>“Really? Um, okay. I guess this is your first timer overload, so company policy mandates I give you some little performance review.” Performance review? Patrick felt his body getting hot again, but he remembered how much easier he made Jacob’s life and relaxed; Jacob would probably be able to look past what he’d claim was an ‘odd little mental block’. Jacob continued, “To be honest, I have a ton of deadlines right now and can’t really spare the time to give you a review right now.”</p>
                <p className='mt-5 indent-5'>See?, Patrick thought. It’s all good. Jacob’s eyes returned to his paperwork and he began writing again.</p>
                <p className='mt-5 indent-5'>“Go talk to Rami, one floor up. Tell him the situation. He should be able to review you.” Patrick felt his heart drop back to the floor.</p>
                <p className='mt-5 indent-5'>“Sure thing”, he replied, and headed out the door.</p>
                <p className='mt-5 indent-5'>Before he was out of earshot, Jacob called out one last remark. “Hey Patrick”. Patrick looked back at him. He was smiling. “I know this is your first time, but don’t worry about it. It’s the type of thing that would take you five minutes.”</p>
                <p className='mt-5 indent-5'>On the next floor, Patrick sat across from Rami, one of the managers on the same level as Jacob. Though they were peers, Rami had a completely different aura about him. Where Jacob was the spitting image of a go-getter employee, the man in front of Patrick had a clear air of irritability about him. He made no attempt to hide his sigh of contempt as Patrick explained his situation.</p>
                <p className='mt-5 indent-5'>“Look, Patrick”, Rami said. “I know who you are. Jacob doesn’t shut up about your work rate or the adaptability of your skills or your good attitude.” Sensing once again that he was about to be let off the hook, Patrick was filled with relief. “Clearly there’s no point for either of us to waste our time on one of these performance reviews. They usually take a couple hours; tell you what, I’ll send you to HR with an assessment recommendation. They’ll have you do an easy 15 minute exam, but it’ll also clear the flag on your name from the timer overload. Sound good?” As he spoke, Rami had begun to lead Patrick out of the door of his office.</p>
                <p className='mt-5 indent-5'>“Look man, I’m really not feeling good today, could I just go home and go through this process another time?” Patrick tried to maintain a calm demeanor as he began to realize how bad failing a simple assessment could look. At this point, Rami had clearly lost interest in whatever Patrick had to say.</p>
                <p className='mt-5 indent-5'>“You’ll be in and out in 15, don’t worry about it”, he replied as he shut the door in Patrick’s face. Patrick stood for a moment, contemplating what he could do in this situation. After coming to the conclusion that he lacked many realistic options, he took the elevator down and returned to his desk.</p>
                <p className='mt-5 indent-5'>After a couple minutes passed, Patrick received another notification on his computer screen. As expected, he was told to report to HR for an assessment. He began to sweat, a sense of impending doom building within him. A couple floors down on the elevator and he was in HR. Unlike the other office spaces he and the rest of the developers spent their time in, the room where Patrick now found himself was relatively silent and empty. Most of their processes had been automated by now. As such, Patrick approached a large monitor on a large wall opposite the room’s entrance. The monitor contained simple information; at the top was a header, displaying the word “Appointments”. Underneath this was only empty space, save for the top left corner. Next to a small pen icon, the entry read:</p>
                <p className='mt-5 indent-5'>“Patrick Durham: Room 1”.</p>
                <p className='mt-5 indent-5'>On the sides of the room, two pairs of closed doors sat opposite each other, each with a number engraved onto a metallic plaque above. Patrick entered the door marked ‘1’ and sat at the desk in the center of the room. On the desk sat a monitor, and on the monitor were instructions on how to begin the exam. Patrick went through the exam, slowly but surely, but the further he progressed, the more it dawned on him that years of honing his craft at swiftly and effectively copying code had done the opposite to his ability to understand basic concepts on his own. Patrick’s body temperature reached new heights, and he found himself drenched in sweat as he exited the room. Though the exam had been a complete failure, Patrick resolved to brush up on his abilities after this was all over. He told himself that he would clear everything up with whatever HR employee he was forced to meet with next, and that one day soon he’d laugh about this whole experience with his friends. Again, Patrick returned to his desk.</p>
                <p className='mt-5 indent-5'>A half-hour later, Patrick sat at a bench outside a small office, waiting to be called into a meeting with a designated HR representative. The door opened, and a young woman’s head peeked out. “Patrick! Why don’t you come on in so we can get started.” The smile on her face lacked warmth, but Patrick nonetheless injected a jolly demeanor into the tone of his response.</p>
                <p className='mt-5 indent-5'>“Sure thing! Let’s figure this all out”, he said with a smile. As he sat on the chair in front of her desk, Patrick psyched himself up. There was no way he would leave this room without showing this woman what an asset to the company he had been, what good work he’d done.</p>
                <p className='mt-5 indent-5'>“My name is Lauren. I presume you know why we’re having this meeting right now?” Her voice was sharp, upbeat, despite the seemingly dire nature of the situation.</p>
                <p className='mt-5 indent-5'>“Yes. Let me start by simply saying that it’s been a rough day for me. I’m not feeling well right now, and I haven’t been able to think clearly.” Patrick ensured he spoke as clearly and calmly as possible, desperate to get through to the woman in front of him.</p>
                <p className='mt-5 indent-5'>“I’m sorry to hear that, Patrick.” Stated smoothly and naturally, Patrick felt her words minimize his best attempts at excusing his own failures. She continued, “Let me be as straightforward as possible about your situation. Company policy dictates that if a developer scores less than a 20% on the novice-level assessment, they will immediately be terminated.”</p>
                <p className='mt-5 indent-5'>Patrick sat in silence for a moment before the words fully sunk in. As they passed through to his brain, the room around him began to spin a little and he began to feel dizzy. “Terminated? Like, fired?” Lauren nodded. “What? I’ve been working here for years! There’s no way I could get fired over something this menial!” Patrick realized that his voice had reached an unprofessional volume, and he promptly muttered an apology and leaned back into his seat. Lauren, unfazed, maintained the same cold smile as she responded.</p>
                <p className='mt-5 indent-5'>“Mr. Durham, the menial nature of the exam is exactly why the company considers its failure to be grounds for termination.” She cleared her throat. “That being said, I’m here to help you. Your supervisor, Mr. Thompson, advocated over the phone that you are in fact a definitive asset to the company. As such, I’m going to pull up your Revenumber; this is a metric kept internally by the company to estimate the profit generated by any given employee. Should we find that your Revenumber exceeds a baseline threshold, you will be put on a performance improvement plan, but you will not be terminated.”</p>
                <p className='mt-5 indent-5'>Patrick could have cried tears of joy. Finally he would be judged on a metric that actually reflected his value as an employee. He began to get excited; he couldn’t wait to see Lauren’s face when she realized he was not only competent, but amazing at his job. Lauren began clicking and typing, searching for Patrick’s information in the database. This continued for a moment before her smile faded for the first time since the meeting had began, and after a few more moments of clicking, she sat still and frowned at her computer. Patrick was ecstatic. That’s right, he thought to himself. Termination my ass. Patrick decided to make the most of this moment.</p>
                <p className='mt-5 indent-5'>“Is something wrong?” He asked, a sincere tone in his voice. Lauren looked up at him, blinked, and looked back at her monitor.</p>
                <p className='mt-5 indent-5'>“I’m sorry, Patrick, but the system isn’t working at the moment due to the internet outage.” Patrick’s excitement faded slightly as he realized she wasn’t reacting to his certainly astronomical Revenumber.</p>
                <p className='mt-5 indent-5'>“Oh, okay. Do we have to reschedule this meeting, then? I tend to be pretty free during the week.” As Lauren responded, her voice held a weighted remorse that Steve wouldn’t have thought was anywhere within her corporate shell.</p>
                <p className='mt-5 indent-5'>“I’m sorry, Patrick. In cases where the Revenumber cannot be determined the policy is to move forward with the original decision. In this case, that would be termination.” For a moment, utter silence. Patrick simply sat and stared at Lauren. It appeared as though the words had passed right through him. She continued, “Please gather your things and empty your desk by the end of the day. We’re sorry to see you go.”</p>
                <p className="mt-5 indent-5">Patrick exited the train at the station just outside his high-rise apartment. In his hands were a box containing all the trinkets he had put at his desk over the years. Soon, he’d no longer be able to afford the rent here and would have to find a more affordable apartment somewhere else. For now, he tried to enjoy the way the sky behind the setting sun gave its warm hues to the window panes.</p>
            </div>
        </div>
        
        
    );
}

export default ImposterSyndrome;