import React from "react";

const SongoftheEarth = () => {
    return(
        <div className="flex items-center flex-col m-10 space-y-5">
            <div className='md:w-9/12 font-inter md:outline outline-1 shadow-stone-500 outline-stone-400 md:shadow-md md:p-10'>
                <div className='font-inter text-center mb-10 font-bold text-6xl'>
                            Song of the Earth; a quick write by me
                </div>
                <div className=' font-semibold text-2xl mt-5'>
                        Postmortem
                </div>
                <p className='mt-5 indent-5'>This story came from a quick write exercise a writing seminar of mine did where I basically wrote something within the span of a few hours without editing or refinement; everything here comes from one shot, and it definitely shows. That being said, it was fun to try and string together something coherent as I carried along. While it's very rough, I did enjoy making this. It is also heavily inspired by some themes and ideas from seinen.</p>
                <h2 className='font-semibold text-2xl mt-5'>Song of the Earth</h2>
                <p className='mt-5 indent-5'>“In times of war, a man must think not about the grim reality of the world; it is  insufficient to accept your surroundings for what they are. Look into the eyes of your  enemy, realize the pain they seek to inflict on you, and look forwards towards a reality  where you have defeated them; that is how you may make it so.” The echo of his  father’s words sounded in Lakshma’s head as he approached his family’s hut, tensed  up and ready to defend himself from any adversaries who lurked in the shadows  casted by the flames around him. As he beheld the small structure, sitting alone on the  outskirts of the village, his eyes burned from the smoke and ash that rose ceaselessly  from the inferno which consumed the wooden and straw buildings behind him.  Lakshma thanked himself that the blaze had yet to reach his home; there may still have  been hope. He approached and banged on the door; no response followed.</p>
                <p className='mt-5 indent-5'>“Father! It’s me!” The door didn’t budge as Lakshma began to repeatedly throw  his weight into it. After a while, he realized his struggle was useless. As strong of a  young man that he had become, something heavy was lodged behind the door.  Lakshma continued to yell out, and after a time, he heard a man’s voice ring out from  behind him.</p>
                <p className='mt-5 indent-5'>“Lakshma… is that you?” Lakshma whipped around at the sound of his father’s voice. At the sight of him, he bounded forward and took the old man into his arms. A feared warrior, Lakshma’s father was once one of the most revered men in the village. Since the surrounding kingdoms decided to begin an all-out war and use their lands as the battlefield, strength had become the benchmark by which men could measure the longevity of their lives. However, as Lakshma looked down into his father’s eyes, he saw no strength, but a deep pain. His rough facial features were traced by blood, and he grimaced at his son’s touch.</p>
                <p className='mt-5 indent-5'>“What happened, father? Who did this to us?”</p>
                <p className='mt-5 indent-5'>“The Kaanites. They came out of nowhere. Burned everything to the ground. The survivors…” Lakshma’s father winced in pain, and began to fall to his knees; his son held him fast, his grip iron, fists petrified by shock. “The survivors scattered. We tried to fight them off, but there were just so many, and they kept coming and coming.” Lakshma laid his father down on the sodden dirt, and as he scanned the man’s broken body, he found four deep wounds in his stomach and chest. Heat began to rise in Lakshma’s chest as he realized he was about to lose his only remaining family. His father tried again to stand, but Lakshma gently pushed him back onto the ground.</p>
                <p className='mt-5 indent-5'>“Don’t move, father. Stay still. You’re going to be okay. You’re going to be fine.” His father laid still for a moment, and let out a soft chuckle.</p>
                <p className='mt-5 indent-5'>“You’ve always been a terrible liar.” The two men sat for a moment, allowing the silence to fill the lungs of their grief. Lakshma’s father lifted his arm, shakily, and placed his hand on his son’s shoulder. “Lakshma… they may return soon. You have to go.” Lakshma began to shake his head, his eyes filling with glass. His father conjured a new sternness, the gentleness in his tone disappearing. “Yes. Go. Remember the strength that I have taught you. The strength to defeat your enemies.” Lakshma knew that this would be the final words he’d hear from his father. As he kissed his father on the forehead, voices began to sound in the distance; the raiders had returned to pillage what remained. As he scurried past the outskirts of the village, into the endless brush, the burning in Lakshma’s eyes was soothed by the tears which he held within them.</p>
                <p className='mt-5 text-center'>*****</p>
                <p className='mt-5 indent-5'>The forest was unforgiving. Days had passed, and the only thing more empty than Lakshma’s heart was his stomach. Long had the trail been lost, and any sense of direction been forgotten. Lakshma travelled aimlessly through the overgrowth, waiting for some signs of civilization, some kind stranger or traveller to lend him a much needed helping hand. As he trekked on, guided only by soft moonlight, Lakshma came across a small clearing. Through the trees on the clearing’s edge, he made out the warm glow of torchlight. On the grass, he saw fives tents arranged in a semi circle. In their center, a large flag tinted a familiar blood red: the colors of the kingdom of Kaanan, one of the main aggressors in the seemingly endless war. Lakshma was hit with a wave of displeasure at its sight. This was the opposite of the friendly traveller that he had been hoping for; the Kaanite military commonly set up forward operating camps in the areas near the village, for the sole purpose of scouting out prime targets that they could raid for resources. It was the dead of night, and it was clear that the camp was silent, so Lakshma formulated a plan to sneak into the village, steal what supplies he could, and continue on his way.</p>
                <p className='mt-5 indent-5'>After a few moments of preparing his knife, he slowly crept into the camp, approaching its center. On a small table next to one of the tents, he found what he was looking for; a couple small containers of rations and a large blade, a tool that would be crucial for navigating the wilderness and protecting himself. Lakshma slowly moved towards his target, dashing from shadow to shadow. As he prepared to make his move on the resources before him, a shout came from behind him, giving sound to words from a language he didn’t understand. Behind him, a man whose robes were dyed with the blood red of Kaanan stood, pointing at him. For a moment, Lakshma froze, calculating the distance between himself, the rations, and the Kaanite watchman. Certainly he had time to grab what he needed and make a run for it. Breaking out into a stride, the traveller took off, and the watchman drew his weapon, a long sword, and pursued him. As the chase ensued, men began to emerge from the surrounding tents in the camp. Lakshma arrived at the table, hurriedly grabbed what he could, and continued running towards the edge of the clearing. The watchman was joined in his chase by numerous other Kaanites, and as Lakshma saw the situation grow increasingly dire, he focused on the brush directly ahead of him and ran as fast as he could.</p>
                <p className='mt-5 indent-5'>After running for some time, the foreign yelling close behind him, Lakshma came across a wide river, one which he’d be unable to cross with his newly acquired spoils in hand. Exhausted, he felt his heart beating against the inside of his chest as he turned around. A group of three Kaanites emerged from the trees, surrounding him, his back to the river. Lakshma muttered a prayer under his breath, asking for the strength to win the battle that he foresaw. The men continued shouting at him in their language, blades in hand. Lakshma raised his sword, head darting between the three men to see which might attack him first. Suddenly, the watchman charged at Lakshma, swinging his sword wildly at his upper body. Lakshma hopped backwards, narrowly dodging the steel tip, and as the watchman tried to stop his forward momentum, he impaled himself on Lakshma’s outstretched blade, colliding into him and sending them over the edge of the river. As they plummeted toward the water, Lakshma’s face was suspended directly in front of the watchman’s. Although the men’s voices were drowned out by the rushing water below, Lakshma understood the Kaanite man perfectly for the first time; as their eyes met, he saw only fear and pain.</p>
                <p className='mt-5 text-center'>*****</p>
                <p className='mt-5 indent-5'>Lakshma awoke to the sun in his eyes and the sound of rushing water in his ears. He may have thought of how he’d possibly survived, or how far the river had washed him away, but the only thing on his mind was his overwhelming hunger. He quickly sat up, scanning the ground beneath him for any signs of the rations that he had stolen. His search revealed only moist soil. As Lakshma began to consider what he could do to quickly eat—try to catch a fish, try to catch a rabbit, try to forage berries or fruit in the forest—he heard a soft humming through the trees. Lakshma re-entered the forest, following the sound of music that struggled to stay afloat upon the wind, until he came across its source. An elderly man with a straw hat, gliding along a path in the forest as if he were a ghost. On his back, the man carried with him a large sack; on his face he carried an unbothered expression as he hummed the soft tune to himself. Surely, Lakshma thought, he had plenty of food in his bag.</p>
                <p className='mt-5 indent-5'>“Excuse me, sir!” As Lakshma yelled out, the man jumped a little bit, and stared at him in silence. “Could you spare some food? Please, sir, I’m starving.”</p>
                <p className='mt-5 indent-5'>The man stood pensively for a moment and frowned. He then looked up at Lakshma, and his expression slowly turned to a smile. “Ah, what brings a young man like you to these parts of the forest?” Lakshma’s stomach raged at him, and he began to feel impatient.</p>
                <p className='mt-5 indent-5'>“Sir, my village burned down. I need food. Please, sir, I’m starving.” The man frowned again.</p>
                <p className='mt-5 indent-5'>“I’m sorry, young man. Everything in my bag is to be given to the nearby kingdoms as tribute. My village needs to pay for protection, you see.” Lakshma looked at the man, becoming increasingly hungry, increasingly impatient. He thought about the constant suffering that it seemed the kingdoms had inflicted upon him, and felt anger begin to take hold. As it did, the man apologized under his breath and began to continue his walk.</p>
                <p className='mt-5 indent-5'>The man stood silently as Lakshma stood before him with his knife drawn. Charged with energy, Lakshma felt his body shake and his heart thump as he blocked the man’s path. “I don’t want to hurt you, sir, but I need your food.” The man frowned and looked at Lakshma with contempt.</p>
                <p className='mt-5 indent-5'>“It’s for my village’s survival, young man. I’m sorry, but I can’t let you have my cargo.” Suddenly, the man turned around and began to run. Lakshma, for a moment startled, gave chase, and while the man surely ran as fast as he can, Lakshma quickly caught up to him, and the man yelled in pain as Lakshma tackled him to the ground. The two wrestled on the grass until Lakshma finally pinned the man down, pointing his knife downward as a threat. Defeated, the man looked upwards at his assailant. He took on a new expression, not one of anger, but of sadness and tired disappointment.</p>
                <p className='mt-5 indent-5'>“That look in your eyes, young man. It reminds me of a rabid animal.” The man let go of his bag and slid backwards, standing up slowly. Lakshma grabbed the bag and sprung to his feet, quickly rummaging through its contents.</p>
                <p className='mt-5 indent-5'>“Look, sir, I’ll only take what I need. You can use the rest of the rations as tax.” After grabbing a couple handfuls of rations, Lakshma raised his head to look back at the man, but he had already disappeared into the forest.</p>
                <p className='mt-5 indent-5'>Far down the path, Lakshma continued down the road. He meandered slowly, feeling as though his legs held the weight of the world. In his mind, the events of the past weeks constantly replayed; he saw images of his father’s eyes as his son left him to die, the Kaanite watchman’s eyes as he took his last breath, the old man’s eyes as he was robbed. Having exhausted his rations and his body, Lakshma searched for a viable place to rest his head for the night. As the sun began to set over the horizon, he heard another song begin playing in the distance. Unlike the humming of the old man, this song didn’t come from someone’s vocal cords; the tone was clean, consistent, soft, comforting. Lakshma vaguely recognized the string instrument whose pleasant notes hit his ears; its sounds carried with them memories of when he was a young boy: sneaking away from intense training sessions with his father to listen to the traveling bards play their music in the village center. For the first time since he watched his home burn, Lakshma felt at peace. The weight on his shoulders lightened, if only a little bit, and the music pushed the painful images out of his mind. As if in a trance, Lakshma began walking toward its source, unsure what awaited him but determined to seek out whatever solace he could find.</p>
                <p className='mt-5 indent-5'>Lakshma arrived at the source of the music: a small wooden cabin, sitting inconspicuously in the center of a grove of trees. Outside, it had begun to rain; the sound of small droplets falling from the sky gave the music a pleasant backing cadence and urged on Lakshma further. Soaking wet, Lakshma knocked on the cabin’s heavy wooden door.</p>
                <p className='mt-5 indent-5'>“Hello? I mean no harm. I was simply drawn to the music.” The instrument’s sound suddenly stopped, and Lakshma stood silently in the cool rain hoping for a response. Suddenly, he heard footsteps approaching the door from the other side. The door opened a small amount, and an elderly woman peered through the crack and into Lakshma’s eyes.</p>
                <p className='mt-5 indent-5'>“You look tired.” Her voice was gruff and marked by years of life in the wilderness. Lakshma hoped that she would extend some hospitality to him.</p>
                <p className='mt-5 indent-5'>“I am, miss. I’ve been traveling for days. I—” Before he could continue, the old woman spoke up again, cutting him off.</p>
                <p className='mt-5 indent-5'>“Young ‘travelers’ like you only ever seek to steal from me or take advantage of an old lady’s hospitality. What’s your goal?” Lakshma went silent for a moment. As he met the old lady’s gaze, her eyes shined with a glimmering intensity, one that reminded him of his father.</p>
                <p className='mt-5 indent-5'>“Miss, I’d like to hear more of your music. I’ve heard nothing like it since I was a young boy. It’s been a rough couple of days and I’d really like to hear more music.” The woman examined Lakshma as if trying to determine the truth of his statement. After a moment, she slammed the door shut. Lakshma’s heart dropped, but as he prepared to continue his trek, the door swung open, and the woman looked up at him with mirth.</p>
                <p className='mt-5 indent-5'>“Good answer”, she chuckled to herself. She motioned to him to enter, and Lakshma stepped inside the small cabin before she shut the door. Inside, the cabin was warm, and held few possessions. On one side, a small cot sat just above the floor. On the other, a fireplace burned. Strewn about were numerous odds and ends: small carved wooden figures, canvases covered in dyes, knitted hats and gloves. “My name is Shmi.”</p>
                <p className='mt-5 indent-5'>“Lakshma”. At the sound of his own name, Lakshma felt strange; it had been a long time since he’d heard it uttered. Shmi motioned toward the cot.</p>
                <p className='mt-5 indent-5'>“Sit down. I’ve got some water boiling for tea.” Lakshma sat on the edge of the cot while Shmi reached into a chest against the wall and produced two small cups. As she poured tea, she told Lakshma how she ended up alone in the forest. In the past, she had been a traveling bard, venturing with her band from village to village and playing music for any who would listen. After giving Lakshma his tea, Shmi sat on a small wooden stool in the center of the cabin and picked up her instrument. “The violin is a bard’s finest weapon. I’ve traveled miles and miles through the harshest country, into the most unknown and mysterious wilds. Nothing is more effective at saving my hide in a rough situation than my violin.” Lakshma sipped his tea in silence, listening intently. “In cities, my music used to be the water that doused bar fights. In the furthest villages, my songs were a stand-in for the common languages that never found their way so far off the beaten path.” Shmi explained that once the kingdoms had begun their ever-expanding and ever-destroying war, being a bard slowly became more and more dangerous. After losing a few of her closest companions to being in the wrong place at the wrong time, she had decided to find an inconspicuous spot and hunker down until the violence died down; it never did.</p>
                <p className='mt-5 indent-5'>“Let me hear it”, Lakshma said. “This music that has saved you in the past.” Shmi took the instrument into her hands. Though its wooden body had once been polished, it now appeared as rough as its owner. However, like Shmi’s technique, the music that the violin produced as Shmi began to play was as elegant and graceful as ever.</p>
                <p className='mt-5 indent-5'>As Shmi played her violin, Lakshma closed his eyes and listened intently. Once again, the melodies put him at peace. He felt the warmth of the fire dancing across his face, and the soft fur of the blanket he sat on in between his fingers. This time, however, his mind wasn’t empty. Shmi’s song brought a newfound melancholy into Lakshma’s heart. He thought about his father, who had always taught him to do whatever he had to for the sake of survival, to seek victory by any means necessary, that strength was all that mattered in this world. For a moment he felt pleased with himself; after all, he had survived up to this point, in spite of all the struggle he had been forced to go through, in spite of the harsh world that he had been thrusted into on his own. The song hit a new note, this one long and pensive, and Lakshma’s thoughts shifted. He remembered the eyes of those he had conquered in his quest for survival. He saw the watchman’s fear, the look of a man who knew his life was about to end, but—unlike his father—wasn’t ready to die. He saw the old man’s sadness, the look of one who had seen a once-innocent boy turned to a savage man, willing to go to any means necessary to ensure the fulfillment of his own hunger. As Lakshma opened his eyes, and the music continued, he looked into the fire, and once again he saw his own village burning. Suddenly, little by little and then all at once, Lakshma began to weep. He wept for the villagers who were killed or forced out of their homes. He wept for the Kaanites who lived lives of violence and war. He wept for the bards who could no longer play their music. He wept for the world. He wept, and Shmi continued her song.</p>
                <p className='mt-5 text-center'>*****</p>
                <p className='mt-5 indent-5'>One morning, the sun shines brightly, and the forest responds in kind; the leaves above his head shine a bright green. As Lakshma kneels before the winding river, light filtered through the canopy turns the mist into a canvas painted by streaks of gold. As he glances down at the water before him, his reflection stares back at him. He smile at the scars on his face; markers of the younger days, when the worst punishments that life had inflicted on him were physical. His eyes return to the forest, then close. Taking in the soft breeze, the gentle mists, the warm rays on his skin, he listens to the music that the Earth beneath his feet creates.</p>
            </div>
        </div>
        
        
    );
}

export default SongoftheEarth;