import React from "react";

const TheBetrayal = () => {
    return(
        <div className="flex items-center flex-col m-10 space-y-5">
            <div className='md:w-9/12 font-inter md:outline outline-1 shadow-stone-500 outline-stone-400 md:shadow-md md:p-10'>
                <div className='font-inter text-center mb-10 font-bold text-6xl'>
                            The Betrayal; a short story by me
                </div>
                <div className=' font-semibold text-2xl mt-5'>
                        Postmortem
                </div>
                <p className='mt-5 indent-5'> I wrote this story in… 10th grade? I find it to be an interesting read, at least for myself. I think I’ve improved since I wrote this, and what I find interesting about it is that it’s… weirdly lacking in voice. I’ve read a lot of fiction since then, and one thing I think (at least hope) I’ve picked up is giving my stories more of a unique voice. I’ve always been one for grand stories, but to me this one rings a bit hollow. It’s curious.</p>
                <h2 className='font-semibold text-2xl mt-5'>The Betrayal</h2>
                <p className='mt-5 indent-5'>They were so close. The night was dark, and the harsh winds brought on by the storm relentlessly buffeted the Ol’ Faithful, a battered wooden ship that had clearly seen its fair share of stormy nights such as this one. But in spite of the weather, they were so, so close. As its tired crew sailed through the rough waves, what remained of their tattered robes desperately clamped onto their bodies, protecting them from the onslaught of the elements. The soft drone of rainfall filled the air with a fresh scent and rhythmic pitter patter, creating a pervasive feeling of peace that clashed violently with the harsh claps of thunder and bright flashes of lightning. At the helm of the ship, the crew’s captain, Jude, stood silently, deep in thought while looking over his crew. Jude knew now that they were so close to the treasure that they had been seeking for ages, and finally they might be able to achieve their dream of becoming the most wealthy pirates in the Sea of Ancients. Although filled with hope and excitement for what the future held, Jude was also filled with appreciation for the sacrifices his crew had made. Painful memories flashed through Jude’s head, temporarily tensing his breath. He remembered the horrors that the crew of the Ol’ Faithful had faced in the deep dark sea. Jude quietly frowned as he remembered the day a mysterious prophet told the crew to fulfill their destiny and uncover the hidden magic of Old King Herod’s treasure, cast away deep in a cave that could be uncovered only by the bravest of souls. What a load of rubbish, Jude thought to himself. For on that fateful day, 21 brave souls set off to find the treasure. Only 12 now remained. Suddenly, Jude’s thoughts were interrupted by the sound of yelling among his crew. </p>
                <p className='mt-5 indent-5'>"Stowaway!” yelled Abe, Jude’s first mate. “Tie him up boys!” a symphony of grunts and muffled yells ensued as the ship’s crew caught and tied up a gruff young man. After being tied up in long strands of rope, the man sat silently in resignation. Jude had already descended to the main deck, eager to find out if this man had been planning to steal the treasure that they seeked. </p>
                <p className='mt-5 indent-5'>Jude gestured silently for his crew to let go of the stowaway. “Your name, boy. Give it now.”</p>
                <p className='mt-5 indent-5'>The boy looked up at Jude. Fear shone in his eyes. “Jessie. Please sir, I only ask that you let me explain-”</p>
                <p className='mt-5 indent-5'>“Silence. I’ll be the only one asking questions here,” Jude hissed. “Why are you on my ship?”</p>
                <p className='mt-5 indent-5'>“Only to warn you of the danger posed by the magical treasure you seek”, said Jessie. The men of the crew began eyeing one another, each wondering where Jessie could have learned the secrets of Herod’s treasure.</p>
                <p className='mt-5 indent-5'>“Tell me, Jessie. Where did you learn of the treasure?” asked Jude. Although his patience had worn thin from weeks at sea, Jude was a very well-tempered man. He would allow Jessie to tell his story. And that he did. Jessie regaled the crew with his tale of agony; one that still continued. In the preceding months, Jessie had been a part of a crew just like this one. They had sailed the sea in hopes of finding Herod’s treasure, they too spurred on by a mysterious man in tattered robes, who had spoken to them of riches and power. After weeks at sea, Jesse’s crew discovered the forbidden sea cave, hidden away under the rubble of centuries of rough waves and storms. When Jessie got to this part of the story, he abruptly stopped. The crewmen could see the pain in his eyes and the torment behind every word he said. </p>
                <p className='mt-5 indent-5'>“We found the treasure, alright. And what do I have to show for it? Fourteen dead crew members. That treasure… is evil.” Jessie went silent, and concerned murmuring arose among the crew. The crew members began to question whether or not they should continue in their search for Herod’s treasure. The captain sat thoughtfully for a few minutes, digesting what he had just heard. All of a sudden, he got up and called for silence among the crew members.</p>
                <p className='mt-5 indent-5'>Jude mustered up his most rousing voice, and said, “My friends. We’ve sailed for weeks. We’ve braved challenges unlike any other. We have faced the enemy, and come out on top. We deserve a reward. This man is a liar!” Murmurs once again broke out amongst the crew, as they considered what their trusted captain had said. The captain spoke up again. “Why would the prophet send us on a wild goose chase for a treasure that isn’t what we think? Clearly this stowaway wants to mislead us, so he may have the treasure for himself!” At this, the crew cried out in solidarity with their captain. Jessie was thrust into the ship’s small brig, and the men continued hastily in their journey towards the forbidden cave. Although most of the crew was set in their ways, and followed the word of Jude, the first mate Abe was having second thoughts. Intrigued by what Jessie had said, Abe waited until the following night to approach the brig so he could ask Jessie some questions.</p>
                <p className='mt-5 indent-5'>Jessie told Abe the secrets of the treasure, and its ability to corrupt those who possessed it, filling them with volatile magic. Abe thought for a moment, and said, “I’ve known the captain for many years. He has saved the men in this crew time and time again from peril. I know in my heart he would never betray us. He is incorruptible.” With this, Abe stood up and returned to his quarters on the ship. After trying and failing to sleep for an hour, Abe realized that deep down, he didn’t completely believe the words he had said. Minutes later, Abe appeared once again outside the brig. “What do I have to do to save my crew?” he asked. Jessie nodded towards a small knife tucked in his belt.</p>
                <p className='mt-5 indent-5'>Jessie said, “When you enter the cave, fire your pistol into the sky. On your signal, I’ll use this knife to escape, and I will destroy the treasure for good.” Abe nodded in understanding, and returned to his quarters, anxious for what the next day would bring.</p>
                <p className='mt-5 indent-5'>The next morning, the sun rose over the ship. The members of the crew slowly stirred from their slumber. An ominous wind blew over the sea, and as Jude looked out to the waves, he made out a small sea cave in the distance. Instantly, he knew what he was laying his eyes upon.</p>
                <p className='mt-5 indent-5'>In a couple of hours, the men stood at the entrance to the cave. Nervously, Abe looked around, drew his pistol, and feigned tripping. Thus, the signal was given, and Jessie began cutting his bindings and cautiously making his way off the ship. </p>
                <p className='mt-5 indent-5'>Inside the cave, an entry filled with dust and grime gave way to a large grotto. Lush grass and natural light illuminated a clear pool in the center. Inside floated a school of rainbow colored fish that swam alone; it was clear that the presence of such creatures could not have occurred without the intervention of a magical force. Pushing on, the crew found itself in an even deeper chamber of the cave, and what they discovered next completely contrasted the picturesque and peaceful setting they had found themselves in within the first chamber of the cave. Before the group of men lay a large pile of skeletons, clearly recently killed. In each skeleton was a deep, red mark. The crew stopped, and a nervous tension arose amongst the sailors. They were unsure what to do next. In spite of this, Jude steeled his resolve and told the men he alone would continue to retrieve the treasure, which appeared to sit on a high, isolated pedestal at the top of the chamber. Slowly, but surely, Jude scaled the walls of the cave, finding footing in every miniscule nook and cranny of the craggy stone structure. After a long, arduous effort, Jude found himself at the apex of his climb. Before taking the treasure into his hands at last, he looked over the remainder of his crew one last time. Tears of pride welled in the captain’s eyes. He solemnly saluted his crew, and, without missing a beat, picked up the golden pendant that lay on the pedestal before him. As he donned the pendant, he was filled with an unknown energy, a magical power which Jude knew would change his life forever. As he looked within, he could see the power now within him. In his mind he visualized a new life, almost as if he were in a trance. Unlimited power. The world bending at his knee. These were the gifts that the pendant promised him if he would only submit to its power.</p>
                <p className='mt-5 indent-5'>“Jude!” The captain’s glance snapped towards the entrance to the chamber. Suddenly, his mind had returned to the present, but the power he now felt inside had not abandoned him. He identified the speaker as none other than Jessie. “Put down the pendant, Jude! It will corrupt you! It will make you turn on those you hold dear!” yelled Jessie in desperation. But Jude was gone. He had heard and heeded the whispers of the pendant. Now, it was his time to take the Sea of Ancients for himself. Jessie and the rest of the crew saw the power coursing through Jude. They knew it would be too powerful for the world to maintain. They knew it would bring only destruction in its path. So, finally, Jessie revealed a gleaming, crystal blade. Jessie quietly exclaimed, “With this blade, I will end the tale of King Herod’s treasure for good.” In a dazzling gleam of sparks and raw energy, Jessie and Jude clashed for the last time.</p>
                <p className='mt-5 indent-5'>Moments later, the cave sat, derelict and empty, filled with the bodies of more dead crewmen. The cave was now ablaze. The pendant no longer sat on its cold, lonely pedestal. One man sat outside the cave, at last victorious in completing his mission.</p>
            </div>
        </div>
        
        
    );
}

export default TheBetrayal;