import React from "react";

const TheDeep = () => {
    return(
        <div className="flex items-center flex-col m-10 space-y-5">
            <div className='md:w-9/12 font-inter md:outline outline-1 shadow-stone-500 outline-stone-400 md:shadow-md md:p-10'>
                <div className='font-inter text-center mb-10 font-bold text-6xl'>
                            The Deep; a short story by me
                </div>
                <div className=' font-semibold text-2xl mt-5'>
                        Postmortem
                </div>
                <p className='mt-5 indent-5'>This story was made last year for my fiction writing class, and takes heavy inspiration from a little bit of blade runner and some other things that I can’t remember rn. Also had an assignment to create an alternate ending, so that’s the one I’ll be posting because I think it’s better. If anyone wants the other one slide into my DMs.</p>
                <h2 className='font-semibold text-2xl mt-5'>The Deep</h2>
                <p className='mt-5 indent-5'>​Dunmoor was an old city. Its layered structure made this evident. Beneath bustling districts of elegant cathedrals and coal factories was the old city, rendered little more than a wooden ruin by the unyielding push of progress. Still further down were the depths, dark recesses untouched by the city’s citizens, spoken only of by parents eager to strike fear into their children. Dunmoor was also a grey city. Even in autumn, the bright hues of red and yellow leaves were nowhere to be seen. The smog-filled sky seemed to choke out the sun, leaving the streets shrouded in a seemingly eternal dusk. These streets were filled with roaming citizens of all ages, and they too were grey. Their skin was pale from long days spent away from the light of the sun, and any color that had been in their garments was blotted out by layers of soot.</p>
                <p className='mt-5 indent-5'>As falling rain was illuminated by the light of golden lanterns which lined the edge of the street, an elegant figure approached a large gate on the side of the road. This figure, a woman, stood out against the unrelenting grayness, her figure clothed by a blood red dress. A hat of the same color sat on her head, embellished by a sleek black feather. Behind the gate perched a tall man in a long black overcoat. His gaunt visage was adorned by a long beak, and his beady eyes made him reminiscent of the crows which sat on the overhangs of the tall mansion behind him. The man regarded the woman through the black bars of the gate with a look of contempt.</p>
                <p className='mt-5 indent-5'>“Your invitation, please.” His voice was uninviting and stern. Without a word, the red woman produced a missive and placed it into the man’s gloved hand. He held it to his face and after some scrutiny, his gaze turned forward. “Lady Austere. Welcome to the Boyle Residence.” The man slunk back into a veil of shadow as the gate slowly creaked open.</p>
                <p className='mt-5 indent-5'>Eleanor Austere was unsure why she found herself attending this party. Yes, it was true that the wealthy upper class of Dunmoor often held mixers for the sake of making important business connections and boosting their own status. But no meaningful connections were to be made that night; after all, it was a masquerade party. Eleanor knew it was unwise to go to a party such as this one, especially a party being held by the Boyles, who were known for having ties with the Cult of the Deep, a mysterious group who worshipped those untold depths beneath Old Dunmoor. By that same token, she reasoned that maybe a party like this was what she needed: a night to let loose and have fun, and an escape from the intense social pressures of her aristocratic lifestyle.</p>
                <p className='mt-5 indent-5'>As Eleanor approached the front entrance of the mansion, she could feel the light from inside warming her against the cool autumn rain. Another tall man, nearly indistinguishable from the man who had accepted her invitation, looked at her from a small compartment which sat just outside the door. “Lady Austere. Master Boyle prepared a special mask for you.” The man disappeared from the small window of his compartment, and after a moment, his beady eyes snapped back into view. He held out an unmarked black box. Eleanor gazed into the open box, and laid her eyes upon the mask which sat within. She picked up the mask and examined it before putting it on. The mask was that of a crow: a long elegant black beak complemented by sleek feathers. With her face concealed, Eleanor stepped into the mansion.</p>
                <p className='mt-5 indent-5'>​As she continued on, Eleanor’s parched eyes lit up, drinking in the bright velvet reds and deep mahogany browns of the building’s huge foyer. She looked around, and felt as though she had stepped into another world. Different animals of all kinds surrounded her, their suits and dresses brightly colored, seemingly sparkling under the light of the polished gold chandelier which hung above them. Their bright garments moved in all directions as they danced to the captivating music coming from a pianist on the edge of the room. Eleanor gladly welcomed this departure from the industrial grey which she had grown accustomed to on her journey through the city.</p>
                <p className='mt-5 indent-5'>“Magnifique, c’est pas? Like a breath of fresh air”, spoke a friendly voice with a strong accent. Behind her, a tall man, this one with the mask of a lion, stood still with his gaze set upon Eleanor. A lion he was indeed, with a golden suit and long blonde hair that blended perfectly with the shimmering mane attached to his mask.</p>
                <p className='mt-5 indent-5'>“Truly. I suppose this is your first time at a Boyle party as well?” Eleanor smiled behind the face of the crow.</p>
                <p className='mt-5 indent-5'>The Lion nodded. “It’s odd. Everyone I’ve met so far has told me it’s their first time. I suppose Monsieur Boyle doesn’t like to see the same faces—or should I say, bodies—twice. Would you like to dance?” Eleanor extended her hand, and as the Lion took it in his, a large voice boomed out from atop the stairs in the front of the room.</p>
                <p className='mt-5 indent-5'>​“Lady Austere! You’ve finally arrived!” Eleanor’s head shot up as she wondered who could be waiting on her with such anticipation. This was a tall man in a stark white suit, which shone with all the luminescence of a full moon in the night sky. On his face sat only half a mask, a white elk with an ivory horn. Somewhat intimidated by the man’s imposing stature, Eleanor reflexively turned her head back to the Lion, but he was already gone, speaking to another small group of partygoers across the room. Eleanor made her way to the man in the elk mask, awaiting an introduction. “Ah, yes, how rude of me. I am Laurence Boyle, head of this estate”, he said with a smile. Despite the warmth of his grin, his eyes remained cold. “I’m glad you’re here, Lady Austere. I want to introduce you to my daughter. She’s a huge fan of your poetry.” Eleanor put on a dry smile as pieces of a puzzle began to assemble in her head. She had wondered why she had been invited to this party in the first place, and was surprised anyone could take a liking to the results of her silly hobby.</p>
                <p className='mt-5 indent-5'>“I’d love to meet her”, she said, almost allowing too much of her eagerness to leak into her inflection. Boyle turned and exited the room, his grin dissipating as he disappeared behind closed doors. Eleanor waited for a moment in confusion at his sudden departure, until the doors reopened and a young woman, seemingly the same age as Eleanor herself, appeared. Eleanor’s heart seemed to skip a beat as she examined the woman. In sharp contrast with the rainbow raiments of the other partygoers, her dress was black as night. To match, long black hair draped across her shoulders. She wore no mask, but Eleanor immediately thought the use of such a covering would be an unforgivable sin; her features were more beautiful than any Eleanor had seen before. As she spoke to Eleanor, icy eyes just like her father’s seemed to bore straight through Eleanor’s crow and right into her pupils.</p>
                <p className='mt-5 indent-5'>“Lovely to meet you, Ms. Austere. My name is Madison.” Her voice was soft, yet perfectly clear above the loud noises of the party.</p>
                <p className='mt-5 indent-5'>“Call me Eleanor.” Madison smiled widely, her eyes flickering with excitement.</p>
                <p className='mt-5 indent-5'>“Sure. I’m a huge fan of your work, Eleanor. I’ve read all your love poems. I swear, when I read your work, it’s like looking through a window into the inner workings of my own heart.” Eleanor felt an unknown warmth rise within her. She knew that her works had garnered popularity, but she had always felt like a fraud. After all, her love poems should have rang empty seeing as they came from her, who had never experienced love at all.</p>
                <p className='mt-5 indent-5'>​“Thank-you”, said Eleanor with a meek smile. Madison’s grin widened.</p>
                <p className='mt-5 indent-5'>“I’m sorry you ended up at one of my father’s dull parties. He insisted upon inviting you after he noticed me reading your book. Let me make it up to you.” Madison reached out and took Eleanor’s hand in hers. They descended the steps, returning to the main area of the party, and began to dance. As their dancing gained speed, they began to laugh loudly. Eleanor, intoxicated by the sounds and sights of the party, kept her gaze on Madison in front of her. As she looked into Madison’s eyes, the grey city and the mundanity of her aristocratic life disappeared. Indeed, Eleanor decided that she had been right to accept Mr. Boyle’s invitation.</p>
                <p className='mt-5 indent-5'>After they had danced for awhile, Madison glanced up at a large clock on the wall. Her face contorted into a small frown, and quickly reverted to a smile as her eyes darted back to Eleanor. “Come with me. I want to show you something far more interesting than this.” Once again, Madison took Eleanor’s hand and led her away. They passed through a seemingly indiscernible maze of halls before coming to a wooden door. Madison opened the door and swiftly darted into the room, and Eleanor, seeing no light coming from within, followed her. As she entered the darkness, she made out Madison’s silhouette on the floor, and laid next to her.</p>
                <p className='mt-5 indent-5'>​“I can’t see anything”, said Eleanor, waiting for some form of explanation from her companion. Her inquisitive silence was met with a soft laugh.</p>
                <p className='mt-5 indent-5'>“Patience.” As they laid in silence, the room suddenly began to fill with light. Eleanor looked above to see a large glass pane where she’d expect a ceiling. Beyond it, stars lit up the sky, escaping the covering of a cloud. They shone brilliantly, more brightly than Eleanor had ever seen before; after all, Dunmoor’s sky was usually covered in smog. As Eleanor’s amazed stare fixed itself on the sky above, Madison’s eyes fell only on her. “Let me see your face, Eleanor.” Eleanor had forgotten the visage of the crow on her face, and as if under Madison’s spell, she immediately removed it. For a time, they watched each other as Madison examined Eleanor’s face. Eleanor felt as though she would like to feel the warmth of Madison’s gaze forever. Slowly, she extended her hand towards Madison’s face. Her arm then froze abruptly, suspended in mid-air.</p>
                <p className='mt-5 indent-5'>"Do you hear that?”, asked Eleanor. Madison looked at her with an almost exaggerated look of confusion.</p>
                <p className='mt-5 indent-5'>“Hear what?”, she responded. Eleanor was unsure of what was happening. She couldn’t articulate what she was hearing. It was as if she was being whispered to, but it was also somewhat of a feeling. She looked down at her mask, which sat on the floor next to her. That was it—the crow—that was the source. Suddenly, she couldn’t remember why she had taken it off. She began to reach for it.</p>
                <p className='mt-5 indent-5'>“I need to get back to the party. I need to put the crow back on.” Eleanor looked at Madison with a completely blank expression. Madison’s eyebrows raised and her expression filled with worry.</p>
                <p className='mt-5 indent-5'>​“Did I do something?” Madison touched Eleanor’s arm. Suddenly, Eleanor’s eyes widened and the crow fell from her hands. Eleanor began to breathe heavily, before calming down and returning to the floor.</p>
                <p className='mt-5 indent-5'>“No, it’s fine. I’m not sure what came over me”, she said. She felt as though she had been awoken from a trance, returned to her senses. Seeking to change the subject, she said, “Your father’s party is incredible. I’ve never seen anything like it.” For a moment, Madison looked up at the stars, and said nothing.</p>
                <p className='mt-5 indent-5'>​“When I was a little girl, I loved Father’s parties too. After awhile, though, they get boring. The spectacle has certainly increased over the years, though. Almost as if it’s his way of compensating for locking me up in this damned mansion.” Eleanor didn’t quite understand what Madison meant, but something about the way Madison spoke made her hang on every word. The muffled sounds of music and merrymaking outside had grown silent. Madison noticed, and tapped Eleanor’s shoulder. “You’d better get going. I think the party is ending.” Eleanor nodded and stood up, but she was reluctant to leave. She felt a new kind of comfort, one that no one else had ever given her.</p>
                <p className='mt-5 indent-5'>Eleanor stepped back into the silent foyer, now empty except for a few stragglers on their way out. Among them, she saw the Lion, who milled about alone, seemingly walking with no discernible pattern. She walked over to him and tapped his shoulder.</p>
                <p className='mt-5 indent-5'>“You never gave me the dance you promised, monsieur”, she said jokingly, now loosened up after her time with Madison. The Lion turned toward her for a moment, and looked at her blankly. Eleanor noticed that his mask seemed to have changed. It now covered more of his face and Eleanor felt as though she could see the sinews below the lion’s skin shifting about. It was as if the mask had replaced his face, its fur sprawling over his countenance. Eleanor stepped back, shocked by the sudden change in his appearance. The Lion turned away, and continued milling about aimlessly, as if bewitched. Eleanor thought that she must be seeing things, and she began to make her way toward the exit.</p>
                <p className='mt-5 indent-5'>“Lady Austere.” Eleanor stopped in her tracks at the sound of a familiar voice. As she turned, she saw Laurence Boyle standing at the front of the foyer, once again atop the staircase with a grin on his face. He beckoned toward her, and, once again, she approached him. “I must thank-you for giving my daughter company. Come with me, Ms. Austere.” Eleanor followed Boyle through another maze of hallways before they entered what appeared to be a library. “It’s late, Eleanor.” She felt the intensity of his stare from both eyes, even as one was covered by the mask of the stag. “My daughter gets lonely in this house. Ever since her mother went missing, it’s been difficult for us. I truly appreciate your keeping her company. As an extension of my gratitude, I’d like you to stay the night”. Even as he expressed his appreciation, Eleanor felt no warmth or compassion in the man’s voice. Nonetheless, his cold stare continued to pierce her, and she swiftly agreed. Without another word, Boyle disappeared into the hallway, and was swiftly replaced by another tall butler in a black overcoat. Eleanor followed him to the room where she’d be sleeping.</p>
                <p className='mt-5 indent-5'>​Laurence Boyle sat alone, in a large music room. Before him were many instruments, all composed of the finest materials. At this moment, however, they went unplayed, and all that could be heard was silence. Suddenly, Laurence said to no-one, “Another successful party. Dozens of new people… sacrificed.”</p>
                <p className='mt-5 indent-5'>Laurence’s voice changed, losing all emotion, and seemingly responding to himself, he said, “Sacrifice? What is being sacrificed? By accepting them into my consciousness, I give them meaning. I give them truth.”</p>
                <p className='mt-5 indent-5'>“Call it what you want. But know that you’ll never have my daughter. Lady Boyle may have been too weak to protect her, but I will. I’ll throw parties forever if I must, if it keeps you from harming her.”</p>
                <p className='mt-5 indent-5'>“Harm? I only seek to give your daughter what I’ve offered all the others. True form. True connection. Do not confuse your fear with wisdom. You have always resisted, but know that your resistance only serves to deny your daughter true meaning. She’ll join me sooner than you know.” Laurence, seemingly angered by what he had said, stood up and stormed out of the room.</p>
                <p className='mt-5 indent-5'>​Eleanor’s eyes snapped open. It was dark, the only light in the room coming from the moon outside a small window next to her bed. She didn’t remember falling asleep, but as she saw her red dress folded neatly on the dresser next to her bed, her red hat on top of it, she felt a renewed comfort. Next to them sat the crow. She frowned, as she didn’t remember picking it up after she left Madison alone. Madison. Eleanor smiled to herself as she thought about Laurence Boyle’s beautiful daughter. As if on cue, the door to her room slowly opened. Eleanor blinked and Madison was sitting on the edge of her bed. Madison wore a white nightgown, and glowed. Her radiance lit up the room around her, and Eleanor felt a warmth return to her body.</p>
                <p className='mt-5 indent-5'>​“I love you, Eleanor”, Madison suddenly said. Her voice was like a song in Eleanor’s ears. “Help me, Eleanor. I need your help. Let me be with you. Take me away with you”. Eleanor lay still, feeling as though she had been hypnotized. She thought that this must be what love felt like.</p>
                <p className='mt-5 indent-5'>​“Yes, Madison. Come with me. I love you, Madison.” Madison smiled.</p>
                <p className='mt-5 indent-5'>​“I need your help. My father won’t let me leave. He keeps me here. He’s trapped me here. Remove his mask. Eleanor, remove his mask.” Barely processing Madison’s words, Eleanor felt her heart flutter. She knew she would do anything for Madison.</p>
                <p className='mt-5 indent-5'>​“I will, Madison. I’ll do it. I’ll help you. I’ll save you. So come with me.” Madison smiled, and leaned over. She gently kissed Eleanor’s forehead.</p>
                <p className='mt-5 indent-5'>Eleanor’s eyes snapped open. Had she fallen asleep again? She wondered if Madison’s visit had been a dream. She thought that was impossible. Suddenly, she remembered what Madison had told her. Eleanor needed to save Madison. It had felt too real to be a dream. Eleanor stood up, and walked towards the door to her room. Eleanor needed to save Madison. She had to remove Laurence Boyle’s mask. She didn’t know how she would find him in this mansion, but she would do it. After putting her dress back on, she stepped back into the hallway. Eleanor needed to save Madison. Eleanor looked around, in a vain attempt to get her bearings. Suddenly, soft laughter rang out to her left. Eleanor immediately recognized it as Madison’s voice, and she began to seek out its source. Eleanor ventured through the hallways, following the soft sounds of Madison’s laughter, which seemed to get closer and closer, yet never arrive. Eleanor needed to save Madison. Eventually, Eleanor found herself at a shut door. This door had been the source of the laughter, yet as she grabbed the handle, the laughter stopped. Eleanor opened the door and peeked inside the room.</p>
                <p className='mt-5 indent-5'>Before Eleanor was a huge courtroom. In front of her stood Laurence Boyle, standing at a raised podium before hundreds of people. Were they people? Rows and rows of standing figures stood one before the other, each holding a candle. They wore masks, standing completely still, and their masks covered their entire faces. These masks were no longer fashioned from artificial materials, but seemed to be fully organic; their eyes were those of animals, some with feathers, others with fur, and scales. Beyond their masks, these figures weren’t human; their bodies consisted only of a dark black robe which draped downward onto the floor. The courtroom seemed to extend with no end, yet its shape contorted as it sloped downward, further and further until all that remained was darkness. Laurence, facing away from Eleanor, stood still, also silent, with his arms stretched outwards towards his unresponsive audience. Eleanor, enraptured, obsessed, noticed none of this, and as her eyes fell on Laurence, she silently walked up to him and prepared to quickly remove his mask. Once she was within arms’ reach, Eleanor reached for Laurence’s mask, and suddenly his eyes turned towards her and widened. Laurence grabbed Eleanor’s arm, and as he did they both fell onto the floor, Eleanor grasping desperately for the stag. “Stop it, Eleanor! What are you doing?! Don’t touch the mask!” Laurence’s voice carried a passion and desperation that Eleanor had not heard from him before. She ignored this.</p>
                <p className='mt-5 indent-5'>​“I need to save Madison”, she said listlessly.</p>
                <p className='mt-5 indent-5'>​“Save Madison?! You’re going to doom her!” Eleanor didn’t know what Laurence was talking about.</p>
                <p className='mt-5 indent-5'>​“I need to save Madison”, she repeated. Eleanor continued to struggle until she got a hold of the horn protruding from Laurence’s mask. In one desperate motion, she ripped the mask off.</p>
                <p className='mt-5 indent-5'>​Laurence’s body suddenly went limp. His eyes remained open. His voice changed, becoming colder, and he looked into Eleanor’s eyes. Even in her obsession, she felt an unparalleled coldness in his stare. “Thank-you, Eleanor. Now, join us.” Suddenly, the room shifted, as if tilting completely sideways. The endless sea of masked figures remained as if glued to the ground, but Eleanor, screaming, plunged into the darkness at the end of the room, and lost consciousness.</p>
                <p className='mt-5 indent-5'>She awoke in darkness. Eleanor—or was it Eleanor? She had forgotten her name. She felt comfort, yet also an unyielding coldness. Before her was an endless sea of black. She knew not how much time had passed. Suddenly, before her was an object. What was it? Ah, yes. It was the crow. She reached out towards the crow. Suddenly, through the mask, she saw the world again. The inside of the mansion. The courtroom, its podium now empty. Now she saw the foyer. She could see outside of the entrance, where excited partygoers gathered. At the front of the foyer, at the top of the stairs, was Madison. Upon her face was the half-mask. The stag. Madison welcomed the first wave of partygoers into the mansion.</p>
            </div>
        </div>
        
        
    );
}

export default TheDeep;