export const CodeProjects = [
    {
        id: 1,
        contentType: 'code',
        title: '3D Voxel Engine',
        description: 'Voxel Engine developed in Unity 3D.',
        pic1Path: 'contentsource/CodeProjects/VoxelEngine/voxelhorizontalscreenshot.png',
        pic2Path: 'contentsource/CodeProjects/VoxelEngine/voxelscreenie.jpg',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'horizontal',
        tags: ['C#', 'Unity', 'Fastnoise', 'Git'],
        githubLink: 'https://github.com/zacharybabers/voxel-experimentation',
    },
    {
        id: 2,
        contentType: 'code',
        title: 'Pirate Defense',
        description: '3D tower defense game where AI uses BFS to detect best path to your base.',
        pic1Path: 'contentsource/CodeProjects/PirateDefense/pirategif.gif',
        pic2Path: 'contentsource/CodeProjects/PirateDefense/piratescreenshot.png',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
        tags: ['C#', 'Unity', 'SourceTree', 'Git'],
        githubLink: 'https://github.com/zacharybabers/Pirate-Defense',
    },
    {
        id: 3,
        contentType: 'code',
        title: 'Keepy Uppies',
        description: '3D Soccer Game where player must collaborate w/ AI to keep ball in the air.',
        pic1Path: 'contentsource/CodeProjects/KeepyUppies/giffy.gif',
        pic2Path: 'contentsource/CodeProjects/KeepyUppies/keepupimage.png',
        media1: true,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
        tags: ['C#', 'Unity', 'Git'],
        githubLink: 'https://github.com/zacharybabers/FootyWithDad',
    },
    {
        id: 4,
        contentType: 'code',
        title: 'Portfolio Website',
        description: 'A simple portfolio website made with vanilla HTML, CSS and JavaScript.',
        pic1Path: 'contentsource/CodeProjects/PortfolioSite/portfoliohorizontal.png',
        pic2Path: 'contentsource/CodeProjects/PortfolioSite/portfoliovertical.png',
        media1: false,
        media2: false,
        layout1: 'horizontal',
        layout2: 'vertical',
        tags: ['HTML', 'CSS', 'JavaScript', 'Animate.css'],
        githubLink: 'https://github.com/zacharybabers/Portfolio-Site',
    }
]